# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-02-22 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('event_date', models.DateField()),
                ('venue', models.CharField(max_length=200)),
                ('manager', models.CharField(max_length=200)),
                ('Desription', models.TextField()),
            ],
        ),
    ]
