# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-02-22 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myposts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='Image',
            field=models.ImageField(default='Null', upload_to='media/'),
        ),
    ]
