# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-02-23 14:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myposts', '0003_auto_20200222_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='event',
            name='venue',
        ),
    ]
